import Link from 'next/link'
import { getAllPosts } from '../lib/posts'
import PostCard from '../components/PostCard'

export default function Home({ posts }: { posts: any[] }) {
  return (
    <main className="max-w-3xl mx-auto p-6">
      <header className="mb-8">
        <h1 className="text-3xl font-bold">我的博客</h1>
        <p className="text-slate-600">基于 Next.js 的个人博客脚手架</p>
      </header>
      <section className="space-y-4">
        {posts.map(p => (
          <PostCard key={p.slug} post={p} />
        ))}
      </section>
      <footer className="mt-12 text-sm text-slate-500">Generated by scaffold</footer>
    </main>
  )
}

export async function getStaticProps() {
  const posts = await getAllPosts()
  return { props: { posts } }
}
